theme: jekyll-theme-minimal
title: DIMO ILIEV,  Senior Technical Product Manager 
description: Bookmark this to keep an eye on my project updates!
# Inside _config.yml or _data/navigation.yml
navigation:
  - title: Home
    url: /https://neuromancerai.github.io/
  - title: About
    url: https://neuromancerai.github.io/about/  # This must match the 'permalink' from your page
    header_pages:
  - about.md
  
defaults:
  - scope:
      path: "" # empty string means all files
    values:
      layout: "single"
      author_profile: true # This shows your bio/social links
      sidebar:
        nav: "main" # Matches the 'main' key in navigation.yml
