remote_theme: "mmistakes/minimal-mistakes"
title: "DIMO ILIEV, Senior Technical Product Manager"
description: "Bookmark this to keep an eye on my project updates!"

# Site Navigation
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/

defaults:
  - scope:
      path: "" 
    values:
      layout: "single"
      author_profile: true
      sidebar:
        nav: "navigation" # This must match the key 'navigation' above
plugins:
  - jekyll-remote-theme
